language: node_js
node_js:
  - "stable"
cache: bundler

scripts:
  test: "npm run test-ci"
after_success:
  - "node mkfile.js"
  - "ls -a ./test"
  - "ls -a"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
